# Generated by Django 2.0.4 on 2018-05-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oddanyGlos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Głos',
                'verbose_name_plural': 'Głosy',
                'db_table': 'Głosy',
                'ordering': ['ID_WYBOROW'],
            },
        ),
        migrations.CreateModel(
            name='osoba',
            fields=[
                ('pesel', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('nr_dowodu', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Osoba głosująca',
                'verbose_name_plural': 'Osoby głosujące',
                'db_table': 'Osoby uprawnione do głosowania',
                'ordering': ['pesel'],
            },
        ),
        migrations.CreateModel(
            name='osobaWybory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kandydat', models.BooleanField(default=False)),
                ('oddalGlos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Osoba-Wybory',
            },
        ),
        migrations.CreateModel(
            name='wybory',
            fields=[
                ('ID_WYBOROW', models.AutoField(primary_key=True, serialize=False)),
                ('nazwaWyborow', models.CharField(max_length=100)),
                ('maxLiczbaKandydatowDoPoparcia', models.IntegerField()),
                ('dataRozpoczecia', models.DateTimeField()),
                ('dataZakonczenia', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Wybory',
                'verbose_name_plural': 'Wybory',
                'db_table': 'Wybory',
                'ordering': ['ID_WYBOROW'],
            },
        ),
        migrations.AddField(
            model_name='osobawybory',
            name='ID_WYBOROW',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.wybory'),
        ),
        migrations.AddField(
            model_name='osobawybory',
            name='pesel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.osoba'),
        ),
        migrations.AddField(
            model_name='oddanyglos',
            name='ID_KANDYDATA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.osoba'),
        ),
        migrations.AddField(
            model_name='oddanyglos',
            name='ID_WYBOROW',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.wybory'),
        ),
        migrations.AlterUniqueTogether(
            name='osobawybory',
            unique_together={('ID_WYBOROW', 'pesel')},
        ),
    ]
