# Generated by Django 2.0.4 on 2018-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='nr_dowodu',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
